import {Inter} from "next/font/google";
import "./globals.css";
import BackgroundStars from "@/app/components/BackgroundStars/BackgroundStars";
// TOASTER
import {Toaster} from "react-hot-toast";


const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Germany Application",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {children}
        <BackgroundStars numStars={200}/>
        <Toaster
            position={"bottom-right"}
            reverseOrder={false}
        />
        </body>
        </html>
    );
}
